🔹 What is Filtering?

Filtering means selecting elements from an array based on conditions.

👉 In NumPy, we use boolean masks for this.

🔹 1. Basic Filtering with Boolean Mask

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

mask = arr > 25     # Boolean mask
print(mask)         # [False False  True  True  True]

filtered = arr[mask]
print(filtered)     # [30 40 50]


[False False  True  True  True]
[30 40 50]


🔹 2. Direct Filtering

Instead of creating a mask separately:

In [2]:
print(arr[arr % 20 == 0])   # [20 40]
print(arr[arr < 35])        # [10 20 30]


[20 40]
[10 20 30]


🔹 3. Filtering in 2D Arrays

In [3]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Get values > 5
print(mat[mat > 5])   # [6 7 8 9]


[6 7 8 9]


🔹 4. Combining Multiple Conditions

Use & (AND), | (OR), ~ (NOT).

⚠️ Wrap each condition in ().

In [4]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[(arr > 20) & (arr < 50)])   # [30 40]
print(arr[(arr == 10) | (arr == 50)]) # [10 50]
print(arr[~(arr > 30)])               # [10 20 30]


[30 40]
[10 50]
[10 20 30]


🔹 5. Example with Strings

In [5]:
fruits = np.array(["apple", "banana", "cherry", "date", "fig"])

print(fruits[fruits != "banana"])      # ['apple' 'cherry' 'date' 'fig']
print(fruits[np.char.startswith(fruits, "c")])  # ['cherry']


['apple' 'cherry' 'date' 'fig']
['cherry']


🔹 6. np.isin() → Filter by Membership

Check if elements belong to a list of values.

In [6]:
arr = np.array([10, 20, 30, 40, 50])

mask = np.isin(arr, [20, 40])
print(arr[mask])   # [20 40]


[20 40]


✅ Summary:

Filtering uses boolean masks (arr[condition]).

Combine conditions with &, |, ~.

Works on numbers, strings, and 2D arrays.

Use np.isin() for membership filtering.