## Reshaping arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

# Reshape From 1-D to 2-D

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


* ⚠ Rules:

* The total number of elements must remain the same (6 elements in this case).

* The new shape must be compatible with the original shape.

# Reshape From 1-D to 3-D


Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#  Using ravel() and flatten()

Both ravel() and flatten() convert a multi-dimensional array into a 1D array.

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ravel())    # Returns a flattened array (view)
print(arr.flatten())  # Returns a flattened array (copy)


[1 2 3 4 5 6]
[1 2 3 4 5 6]


#### Difference:

* ravel() returns a view (modifying it affects the original array).

* flatten() returns a copy (modifying it does not affect the original array).

## Using resize()

Unlike reshape(), resize() modifies the array in place.

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize(3, 2)  # Changes shape permanently

print(arr)

[[1 2]
 [3 4]
 [5 6]]


## Using np.newaxis to Add Dimensions


You can add extra dimensions using np.newaxis.


In [23]:
arr = np.array([1, 2, 3,4])

print(arr[np.newaxis, :])  # Adds a new row dimension
print(arr[:, np.newaxis])  # Adds a new column dimension

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


### Using np.expand_dims()

This is another way to add dimensions.

In [28]:
arr = np.array([1, 2, 3])
expanded = np.expand_dims(arr, axis=0)  # Adds a new axis at position 0

# print(arr.shape)
print(expanded.shape)  # (1, 3)

(1, 3)


### Transposing with T and transpose()


You can swap rows and columns using .T or transpose().

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr.T)  # Transposes the array

[[1 4]
 [2 5]
 [3 6]]


### Changing Shape with reshape(-1, N)


Using -1 automatically infers the missing dimension.

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.reshape(-1, 3))  # Automatically calculates the number of rows

[[1 2 3]
 [4 5 6]]


reshape()	     === Change shape while keeping elements constant

ravel()	        ===  Flatten the array (view)

flatten()	  ===  Flatten the array (copy)

resize()	===      Modify the shape in place newaxis	Add an extra dimension

expand_dims()	===  Expand dimensions explicitly

T / transpose()	===  Transpose the array

reshape(-1, N)	===  Automatically determine one dimension