# NumPy Array Iterating


### Iterating Arrays


Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

### 1. Iterating Over 1D Arrays


A simple for loop can be used to iterate over a one-dimensional array.



In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

for element in arr:
    print(element)


1
2
3
4
5


### 2. Iterating Over 2D Arrays (Row-wise)


For 2D arrays, iterating normally gives row-wise elements.


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# print(arr)
for row in arr:
    print(row)


[1 2 3]
[4 5 6]


### Iterating Over Individual Elements (Nested Loop)


To access individual elements, use nested loops:

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for row in arr:
    for element in row:
        print(element, end=" ")

1 2 3 4 5 6 

### 3. Iterating Using nditer()

The numpy.nditer() function allows iterating over each element efficiently.

In [ ]:
for element in np.nditer(arr):
    print(element, end=" ")

1 2 3 4 5 6 

### 4. Iterating with Different Order (F and C Modes)


* order='C' iterates row-wise (default).

* order='F' iterates column-wise.

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Column-wise iteration
for element in np.nditer(arr, order='F'):
    print(element, end=" ")
# print(arr)

1 4 2 5 3 6 

### 5. Iterating with Modification (op_flags)


To modify elements while iterating, set op_flags=['readwrite'].

In [26]:
arr = np.array([1, 2, 3, 4])

for element in np.nditer(arr, op_flags=['readwrite']):
    element[...] *= 2  # Modify in place

print(arr)


[2 4 6 8]


### 6. Iterating with an Index (ndenumerate())


To get the index of each element, use ndenumerate().

In [8]:
arr = np.array([[1, 2], [3, 4]])

for index, value in np.ndenumerate(arr):
    print(f"Index {index} → {value}")


Index (0, 0) → 1
Index (0, 1) → 2
Index (1, 0) → 3
Index (1, 1) → 4


### 7. Iterating Over Multiple Arrays with nditer()


If you need to iterate over multiple arrays at once, use flags=['external_loop'].

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

for x, y in np.nditer([arr1, arr2]):
    print(x, y)


1 4
2 5
3 6
