# NumPy Searching Arrays

🔹 1. np.where() → Find Indexes

Returns the indexes of elements that match a condition.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Find indexes where arr == 30
idx = np.where(arr == 30)
print(idx)   # (array([2]),)

# Find indexes where arr > 25
idx2 = np.where(arr > 25)
print(idx2)  # (array([2, 3, 4]),)


(array([2]),)
(array([2, 3, 4]),)


🔹 2. np.searchsorted() → Binary Search Index

Finds the position where an element should be inserted to keep the array sorted.

In [2]:
arr = np.array([10, 20, 30, 40, 50])

pos = np.searchsorted(arr, 35)
print(pos)   # 3 → 35 should go before 40


3


You can control side (left or right):

In [3]:
pos = np.searchsorted(arr, 20, side='right')
print(pos)   # 2 → after 20


2


🔹 3. np.nonzero() → Find Non-Zero Elements

Returns indexes of all non-zero elements.

In [4]:
arr = np.array([0, 1, 0, 2, 3, 0])

idx = np.nonzero(arr)
print(idx)   # (array([1, 3, 4]),)


(array([1, 3, 4]),)


🔹 4. Boolean Indexing (Search with Conditions)

You can directly filter values:

In [5]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])   # [30 40 50]
print(arr[arr % 20 == 0])  # [20 40]


[30 40 50]
[20 40]


🔹 5. Example with 2D Arrays

In [6]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Find where element == 5
idx = np.where(mat == 5)
print(idx)         # (array([1]), array([1]))
print(mat[idx])    # [5]


(array([1]), array([1]))
[5]


✅ Summary:

np.where() → Indexes matching condition

np.searchsorted() → Insertion index (binary search)

np.nonzero() → Indexes of non-zero values

Boolean indexing → Directly filter elements