# What is NumPy?

* NumPy stands for Numerical Python.

* It is used for:

    * Working with arrays (much faster than Python lists).

    * Performing mathematical operations.

    * Handling linear algebra, statistics, random numbers, and more.

🔹 Installation

In [ ]:
# pip install numpy

Import it in Python (commonly as np):    

In [1]:
import numpy as np

🔹 Creating Arrays

NumPy mainly works with ndarray (n-dimensional array).

In [1]:
import numpy as np

# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# 2D Array (Matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Array filled with zeros
zeros = np.zeros((2, 3))
print(zeros)

# Array filled with ones
ones = np.ones((3, 3))
print(ones)

# Range of numbers
arr3 = np.arange(0, 10, 2)  # start=0, stop=10, step=2
print(arr3)

# Evenly spaced numbers
arr4 = np.linspace(0, 1, 5)
print(arr4)

arr5 = np.identity(3)
print(arr5)

arr6 = np.eye(4)
print(arr6)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


🔹 Basic Array Operations

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr + 5)   # Add 5 to each element
print(arr * 2)   # Multiply each element by 2
print(arr ** 2)  # Square each element

# Mathematical functions
print(np.sqrt(arr))   # Square root
print(np.mean(arr))   # Mean
print(np.max(arr))    # Max value
print(np.min(arr))    # Min value
print(np.sum(arr))    # Sum of all elements
print(np.std(arr))    # Standard deviation
print(np.median(arr)) # Median
print(np.var(arr))    # Variance

🔹 Indexing & Slicing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])     # First element
print(arr[-1])    # Last element
print(arr[1:4])   # Slice from index 1 to 3
print(arr[:3])    # First three elements
print(arr[::2])   # Every 2nd element