🔹 1. np.sort() → Returns a Sorted Copy

In [1]:
import numpy as np

arr = np.array([30, 10, 50, 20, 40])
sorted_arr = np.sort(arr)

print("Original:", arr)       # [30 10 50 20 40]
print("Sorted Copy:", sorted_arr)  # [10 20 30 40 50]


Original: [30 10 50 20 40]
Sorted Copy: [10 20 30 40 50]


✅ Original array stays the same.

🔹 2. ndarray.sort() → Sort In-Place

In [2]:
arr = np.array([30, 10, 50, 20, 40])
arr.sort()   # modifies original array
print(arr)   # [10 20 30 40 50]


[10 20 30 40 50]


🔹 3. Sorting Strings

In [3]:
arr = np.array(["banana", "apple", "cherry"])
print(np.sort(arr))   # ['apple' 'banana' 'cherry']


['apple' 'banana' 'cherry']


🔹 4. Sorting Booleans

In [4]:
arr = np.array([True, False, True])
print(np.sort(arr))   # [False  True  True]


[False  True  True]


🔹 5. Sorting 2D Arrays

In [5]:
mat = np.array([[3, 2, 1],
                [6, 5, 4]])

print(np.sort(mat))          # Sorts each row
# [[1 2 3]
#  [4 5 6]]

print(np.sort(mat, axis=0))  # Sort column-wise
# [[3 2 1]
#  [6 5 4]]


[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]


🔹 6. Argsort → Get Sorted Indexes

Instead of sorting values, get the indices that would sort the array.

In [6]:
arr = np.array([30, 10, 50, 20, 40])
idx = np.argsort(arr)

print(idx)        # [1 3 0 4 2]
print(arr[idx])   # [10 20 30 40 50]


[1 3 0 4 2]
[10 20 30 40 50]


🔹 7. Lexsort → Sort by Multiple Keys

Useful for sorting by 2 conditions (like Excel multiple-column sort).

In [7]:
names = np.array(['John', 'Jane', 'Alice', 'Bob'])
ages = np.array([25, 30, 25, 20])

idx = np.lexsort((names, ages))  
print(idx)        # [3 2 0 1]
print(names[idx]) # ['Bob' 'Alice' 'John' 'Jane']


[3 2 0 1]
['Bob' 'Alice' 'John' 'Jane']


👉 First sorts by ages, then by names if ages are equal.

✅ Summary:

np.sort() → Returns sorted copy

.sort() → Sort in-place

np.argsort() → Indices of sorted array

np.lexsort() → Multiple key sorting

Works on numbers, strings, booleans, 1D & 2D