🔹 1. Basic Indexing

Like Python lists, NumPy arrays use zero-based indexing.

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])   # First element → 10
print(arr[2])   # Third element → 30
print(arr[-1])  # Last element → 50
print(arr[1:4]) # Elements from index 1 to 3 → [20 30 40]

10
30
50
[20 30 40]


🔹 2. Slicing 1D Arrays

Syntax: array[start:end:step]

start → index where slice begins (default = 0)

end → index where slice ends (not included)

step → interval (default = 1)

In [ ]:
print(arr[1:4])   # [20 30 40]
print(arr[:3])    # [10 20 30]  (from start)
print(arr[2:])    # [30 40 50]  (till end)
print(arr[::2])   # [10 30 50]  (every 2nd element)
print(arr[::-1])  # [50 40 30 20 10] (reverse array)


🔹 3. Indexing in 2D Arrays

For matrices (2D arrays), use [row, column].

In [6]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(mat[0, 0])  # First row, first column → 1
print(mat[1, 2])  # Second row, third column → 6
print(mat[-1, -1]) # Last row, last column → 9


1
6
9


🔹 4. Slicing in 2D Arrays

In [7]:
# Get first two rows and columns
print(mat[:2, :2]) 
# [[1 2]
#  [4 5]]

# Get first column
print(mat[:, 0])  # [1 4 7]

# Get last row
print(mat[-1, :])  # [7 8 9]

# Get middle column
print(mat[:, 1])  # [2 5 8]


[[1 2]
 [4 5]]
[1 4 7]
[7 8 9]
[2 5 8]


🔹 5. Fancy Indexing

You can use a list of indices.

In [3]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 2, 4]])


[10 30 50]


For 2D arrays:

In [8]:
print(mat[[0, 2], [1, 2]])

[2 9]


🔹 6. Boolean Indexing

You can filter values with conditions:

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])
print(arr[arr % 20 == 0])