# Joining NumPy Arrays


Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

### 1. Using concatenate()


The numpy.concatenate() function joins arrays along a specified axis.

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2))
print(result)


[1 2 3 4 5 6]


For multi-dimensional arrays, specify the axis:

In [3]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.concatenate((arr1, arr2), axis=0)  # Vertical join
print(result)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 2. Using stack()


The numpy.stack() function joins arrays along a new axis.

In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.stack((arr1, arr2), axis=0)  # Stacks along rows
print(result)


[[1 2 3]
 [4 5 6]]


To stack along columns (axis=1):

In [5]:
result = np.stack((arr1, arr2), axis=1)
print(result)


[[1 4]
 [2 5]
 [3 6]]


### 3. Using hstack() (Horizontal Stack)


The numpy.hstack() function stacks arrays horizontally (column-wise).



In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.hstack((arr1, arr2))
print(result)


[1 2 3 4 5 6]


For 2D arrays:

In [7]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.hstack((arr1, arr2))
print(result)


[[1 2 5 6]
 [3 4 7 8]]


### 4. Using vstack() (Vertical Stack)


The numpy.vstack() function stacks arrays vertically (row-wise).



In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.vstack((arr1, arr2))
print(result)


[[1 2 3]
 [4 5 6]]


### 5. Using dstack() (Depth Stack)


The numpy.dstack() function stacks arrays along the third dimension (depth).



In [1]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.dstack((arr1, arr2))
print(result)


NameError: name 'np' is not defined

This creates a 3D array with shape (1, 3, 2), adding a new depth dimension.

