# 📘 Random Permutations in NumPy

Random permutations are used to shuffle data or generate a new ordering of elements.
This is common in machine learning (shuffling datasets), games, and simulations.

🔹 1. numpy.random.permutation()

    Returns a new array with randomly permuted order.

    The original array is not changed.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(np.random.permutation(arr))   # Shuffled copy
print(arr)                          # Original unchanged


[1 4 2 3 5]
[1 2 3 4 5]


🔹 2. numpy.random.shuffle()

Shuffles the array in place (modifies the original).

In [2]:
arr = np.array([1, 2, 3, 4, 5])

np.random.shuffle(arr)
print(arr)   # Original is shuffled

[2 4 1 5 3]


🔹 3. Permutation of Integers

You can directly shuffle a range of integers:

In [3]:
print(np.random.permutation(10))   # Random order of 0–9

[5 9 2 0 4 8 1 7 6 3]


🔹 4. Using the New Generator API (Recommended)

In [4]:
rng = np.random.default_rng()

arr = np.array([10, 20, 30, 40, 50])

print(rng.permutation(arr))   # Shuffled copy
rng.shuffle(arr)              # In-place shuffle
print(arr)


[40 10 30 50 20]
[40 10 50 30 20]


🔹 5. Difference Between permutation() and shuffle()

| Function      | Returns   | Modifies Original? | Example Use Case                       |
| ------------- | --------- | ------------------ | -------------------------------------- |
| `permutation` | New array | ❌ No               | When you need a shuffled copy          |
| `shuffle`     | None      | ✅ Yes              | When you want to shuffle data directly |


✅ Tip:

Use shuffle() when preparing datasets for training ML models.

Use permutation() when you need both the original and a shuffled copy.