In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.append(arr, [6, 7, 8])
print(arr)
print(new_arr)

[1 2 3 4 5]
[1 2 3 4 5 6 7 8]


In [3]:
arr = np.array([1, 2, 3])
print(arr.dtype)
int_arr = np.array([1, 2, 3])
print(int_arr.astype(float))


int64
[1. 2. 3.]


In [4]:
arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([6, 7, 8, 9, 10])
new_arr = np.concatenate((arr, arr1))
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
new_arr = np.insert(arr, 2, [11, 12])
print(new_arr)

[ 1  2 11 12  3  4  5]


In [14]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
new_arr_2d = np.insert(arr_2d, 1, [7, 8, 9], axis=0)
print(new_arr_2d)
new_arr_2d_axis1 = np.insert(arr_2d, 1, [7, 8], axis=1) 
print(new_arr_2d_axis1)

[[1 2 3]
 [7 8 9]
 [4 5 6]]
[[1 7 2 3]
 [4 8 5 6]]


In [12]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
new_arr_3d = np.insert(arr_3d, 1, [[9, 10], [11, 12]], axis=0)
print(new_arr_3d)
print(arr_3d[arr_3d > 2])
print(np.where(arr_3d % 2 == 0))

[[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]]]
[3 4 5 6 7 8]
(array([0, 0, 1, 1]), array([0, 1, 0, 1]), array([1, 1, 1, 1]))


In [17]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
new_arr = np.delete(arr, 2)
print(new_arr)

[1 2 3 4 5]
[1 2 4 5]


In [20]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
new_arr_2d = np.delete(arr_2d, 1, axis=0)
print(new_arr_2d)

[[1 2 3]]
